#!/bin/bash

APP=Deluge
PORT=8112
MOUNT="/cloud"
LOG="/logs/health"

exit 0

NS=$(which netstat)
X=${?}

if [[ ${X} -ne 0 ]];
then
	# netstat is missing
	echo $(date) - ${APP} - Installing net-tools >> ${LOG}
	apk update
	apk add --update net-tools util-linux grep
fi

${NS} -ntlp | grep :${PORT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} service not running >> ${LOG}
	exit 1			# Port not open
fi

mountpoint ${MOUNT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} - Rclone mount failed >> ${LOG}
	exit 2			# Rclone mount failed
fi

if ! [[ -d ${MOUNT}/$(basename ${MEDIA}) ]]
then
	echo $(date) - ${APP} - MEDIA missing >> ${LOG}
	exit 2			# Rclone mount emptt
fi

exit 0
