#!/bin/bash

APP=Ersatz.TV
PORT=8409
MOUNT="/media"
LOG="/logs/health"
NS=$(which netstat)

if [[ ${?} -ne 0 ]];
then
	# No netstat so install it and create new log file
	echo $(date) - ${APP} - Installing net-tools >> ${LOG}
	apt update
	apt install net-tools -y
fi

/bin/netstat -ntlp | grep :${PORT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} service not running >> ${LOG}
	exit 1			# Port not open
fi

mountpoint ${MOUNT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} - Rclone mount failed >> ${LOG}
	exit 2			# Rclone mount failed
fi

if ! [[ -f ${MOUNT}/omnimounted ]];
then
	echo $(date) - ${APP} - Media failure >> "${LOG}"
	exit 3			# External mapping present but no cloud
fi

exit 0
