#!/bin/bash

mountpoint -q /mnt/$(basename ${MERGEMOUNT})
if [[ ${?} -ne  0 ]];
then
	exit 1			# MergerFS mount failed
fi

mountpoint -q /mnt/$(basename ${RCLONEMOUNT})
if [[ ${?} -ne  0 ]];
then
	exit 2			# Rclone mount failed
fi

if ! [[ -d /mnt/$(basename ${RCLONEMOUNT})/$(basename ${MEDIA}) ]];
then
	exit 3			# Media missing
fi

if ! [[ -f /mnt/$(basename ${RCLONEMOUNT})/$(basename ${MEDIA})/omnimounted ]];
then
	exit 4			# External mapping present but no cloud
fi

exit 0
