#!/bin/bash

APP=Prowlarr
PORT=9696
LOG="/config/logs/health"
NS=$(which netstat)

if [[ ${?} -ne 0 ]];
then
	# No netstat so install it and create new log file
	echo $(date) - ${APP} - Installing net-tools >> ${LOG}
	apt update
	apt install net-tools -y
fi

${NS} -ntlp | grep :${PORT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} service not running >> ${LOG}
	exit 1			# Port not open
fi

exit 0
