#!/bin/bash

APP=SABnzbd
PORT=8080
MOUNT="/cloud"
LOG="/logs/health"

X=$(which at)
X1=${?}
X=$(pidof atd)
X2=${?}
NS=$(which netstat)
X3=${?}
((X=X1+X2+X3))

if [[ ${X} -ne 0 ]];
then
	# At least one of at, atd, and netstat are missing
	echo $(date) - ${APP} - Installing at and net-tools and starting atd >> ${LOG}
	apk update
	apk add --update at net-tools util-linux grep
	printf "root\nabc" > /etc/at.allow
	atd
fi

${NS} -ntlp | grep :${PORT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} service not running >> ${LOG}
	exit 1			# Port not open
fi

mountpoint ${MOUNT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} - Rclone mount failed >> ${LOG}
	exit 2			# Rclone mount failed
fi

if ! [[ -d ${MOUNT}/$(basename ${MEDIA}) ]]
then
	echo $(date) - ${APP} - MEDIA missing >> ${LOG}
	exit 2			# Rclone mount empty
fi

exit 0
