#!/bin/bash

APP=SABnzbd
PORT=8080
MOUNT="/cloud"
LOG="/logs/health"

X=$(which at)
X1=${?}
X=$(pidof atd)
X2=${?}
NS=$(which netstat)
X3=${?}
((X=X1+X2+X3))

if [[ ${X} -ne 0 ]];
then
	# At least one of at, atd, and netstat are missing
	echo $(date) - ${APP} - Installing at and net-tools and starting atd >> ${LOG}
	apt update
	apt install at net-tools -y
	atd
fi

${NS} -ntlp | grep :${PORT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} service not running >> ${LOG}
	exit 1			# Port not open
fi

mountpoint ${MOUNT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} - Rclone mount failed >> ${LOG}
	exit 2			# Rclone mount failed
fi

exit 0
