#!/bin/bash

APP=TransVPN
PORT=9091
MOUNT="/cloud"
LOG="/logs/health"

X=${?}

NS=$(which netstat)

if [[ ${?} -ne 0 ]];
then
	# No netstat so install it and create new log file
	echo $(date) - ${APP} - Installing net-tools >> ${LOG}
	apt update
	apt install net-tools -y
	NS=$(which netstat)
fi

${NS} -ntlp | grep :${PORT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} service not running >> ${LOG}
	exit 1			# Port not open
fi

mountpoint ${MOUNT}
if [[ ${?} -ne  0 ]];
then
	echo $(date) - ${APP} - Rclone mount failed >> ${LOG}
	exit 2			# Rclone mount failed
fi

if ! [[ -d ${MOUNT}/$(basename ${MEDIA}) ]]
then
	echo $(date) - ${APP} - MEDIA missing >> ${LOG}
	exit 2			# Rclone mount empty
fi

exit 0
