#!/bin/bash

# Run as USER, not root/sudo

if [ $(id -u) = "0" ]
then
	echo Omni Setup needs to be run as the user, not root.  SUDO will be used for root-level access where applicable.
	exit 1
fi

sudo apt update
sudo apt install git-core

cd /opt
sudo mkdir -p OmniStream
sudo chown -R ${USER}:${USER} OmniStream
git clone https://github.com/kelinger/OmniStream.git

if [[ ${?} != 0 ]]
then
	echo
	echo This is meant to be run on a system that has not yet been setup.  Use the update menu within Omni to bring
	echo the project up-to-date or clear the /opt/OmniStream directory and rerun setup to start fresh.
	echo
	exit 2
fi

# Modify .bashrc

# Install/update  Docker and Compose

# Install SystemD services

# Set home folders for personalizations

# Start setup menu for parameters and help
