#!/bin/bash

# Run as USER, not root/sudo

if [ $(id -u) = "0" ]
then
	echo Omni Setup needs to be run as the user, not root.  SUDO will be used for root-level access where applicable.
	exit 1
fi

VERSION=$(lsb_release -si)

# Install dependencies

echo Installing/verifying dependencies... 
sudo apt update > /dev/null 2>&1
APPLIST=" \
	acl \
	apache2-utils \
	apt-transport-https \
	at \
	bc \
	ca-certificates \
	curl \
	dialog \
	fuse \
	git-core \
	htop \
	jq \
	parallel \
	pigz \
	pv \
	python3-pip \
	rsync \
	software-properties-common \
	speedometer \
	speedtest-cli \
	unzip \
	vnstat \
	wget \
	"
for i in ${APPLIST}; do
	echo -n $i...
	sudo apt install -y $i > /dev/null 2>&1
	if [[ ${?} = 0 ]]
	then
		echo Done
	else
		echo Failed!
		exit 11
	fi
done

# Clone OmniStream to /opt

echo -n Grabbing OmniStream from GIT...
cd /opt
sudo mkdir -p OmniStream
sudo chown -R ${USER}:${USER} OmniStream
git clone https://github.com/kelinger/OmniStream.git > /dev/null 2>&1

if [[ ${?} = 0 ]]
then
	echo Done
else
	echo
	echo This is meant to be run on a system that has not yet been setup.  Use the update menu within Omni to bring
	echo the project up-to-date or clear the /opt/OmniStream directory and rerun setup to start fresh.
	echo
	echo This message may also be displayed if the download from GIT failed.  If this is the case \(no /opt/OmniStream\)
	echo then simply rerun the setup.
	echo
	exit 12
fi

# Install Docker

echo -n Installing Docker...

curl -fsSL https://get.docker.com | sh > /dev/null 2>&1

if [[ ${?} = 0 ]]
then
	echo Done
else
	echo Failed!
	exit 13
fi

# Install Docker Compose

echo -n Installing Docker Compose...

cd /tmp
curl -s https://api.github.com/repos/docker/compose/releases/latest | grep browser_download_url  | grep docker-compose-linux-x86_64 | cut -d '"' -f 4 | wget -qi -
if [[ ${?} = 0 ]]
then
	chmod +x docker-compose-linux-x86_64
	sudo mv docker-compose-linux-x86_64 /usr/local/bin/docker-compose
	echo Done
else
	echo Failed!
	exit 14
fi

# Allow current user to control Docker

echo Granting Docker permissions to ${USER}
sudo usermod -aG docker ${USER}
sudo gpasswd -a ${USER} docker
sudo setfacl -m user:${USER}:rw /var/run/docker.sock

# Modify .bashrc

echo Updating .bashrc
#sed -zi '/source \/opt\/OmniStream\/bin\/omni_aliases/!s/$/\nsource \/opt\/OmniStream\/bin\/omni_aliases\n/' ~/.bashrc
#sed -zi '/source \/opt\/OmniStream\/bin\/omni_functions/!s/$/\nsource \/opt\/OmniStream\/bin\/omni_functions\n/' ~/.bashrc
#sed -zi '/source \/opt\/OmniStream\/bin\/omni_complete/!s/$/\nsource \/opt\/OmniStream\/bin\/omni_complete\n/' ~/.bashrc
sed -zi '/source \/opt\/OmniStream\/bin\/omni_init/!s/$/\nsource \/opt\/OmniStream\/bin\/omni_init\n/' ~/.bashrc

# Install services

echo Setting up services
sudo systemctl start vnstat
sudo systemctl enable vnstat
sudo sed -i 's/^#user_allow_other/user_allow_other/g' /etc/fuse.conf

# Make system Omni-ready

echo Setting up Omni paths and functions
pip3 install --upgrade pip > /dev/null 2>&1
pip install --upgrade pip > /dev/null 2>&1
mkdir -p /opt/OmniStream/enabled /opt/OmniStream/logs ~/Omni/Configs ~/Omni/mnt
o+ 001-header.yaml 002-traefik.yaml 999-footer.yaml

# Start setup menu for parameters and help

echo
/opt/OmniStream/bin/make-env

### Output results

source /opt/OmniStream/bin/omni_init
source /opt/OmniStream/.env
echo Distribution is ${VERSION}
docker -v
docker-compose -v
echo Customizations in ${ENV}
echo
echo Now would be a really good time to reboot your server
